### ISSUE TITLE
webhook_config.yaml is missing in the repository

### ISSUE THREAD

**Issue by samsanmugam** [banzaicloud/dast-operator#1]
**Describe the bug**

The file webhook_config.yaml mentioned in one of the steps to install the dast-operator is missing in the repository.

**Steps to reproduce the issue:**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pbalogh-sa** [comment]
@samsanmugam Thanks for reporting this. We will fix it.

**Comment by pbalogh-sa** [comment]
`make deploy` will install the `ValidatingWebhookConfiguration` as well

**Comment by samsanmugam** [comment]
Thanks Peter. I will try that.

________________________________
