### ISSUE TITLE
Chart install fails with no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by mickengland** [banzaicloud/dast-operator#41]
**Describe the bug**
When trying to install the helm chart on minikube running Server Version: v1.22.1 it fails with this error:

```
Error: failed to install CRD crds/security.banzaicloud.io_dasts.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

**Steps to reproduce the issue:**
```
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm install dast-operator banzaicloud/dast-operator
```

**Expected behavior**
Expected chart to install

**Screenshots**
N/A

**Additional context**
minikube version: v1.23.0
helm version: version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}

**Comment by pbalogh-sa** [comment]
@mickengland Thanks for reporting this. We will fix it soon.

**Comment by pbalogh-sa** [comment]
@mickengland I've just merged the fix.
